### ISSUE TITLE
[Idea] Remove all paths from search input

### ISSUE THREAD

**Issue by osbre** [Astrotomic/ignition-stackoverflow#6]
**Is your feature request related to a problem? Please describe.**
Without a path we will get more results, i think

**Describe the solution you'd like**
Match all paths and remove them.

**Describe alternatives you've considered**
Just leave it as is :eyes:

**Additional context**

**Comment by Gummibeer** [comment]
Hey,

that's the code that generates the API search URL.
https://github.com/Astrotomic/ignition-stackoverflow/blob/8bbe93fc5670c47b2f72615002fb97c3cf78fc41/src/StackOverflowSolutionProvider.php#L91-L111
What do you want to change? My primary question is: what do you mean with "path"? 🤔
Do you mean the FQCN of the exception of the exception has no message?

**Comment by osbre** [comment]
Error example:

`
syntax error, unexpected 's' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) (View: /home/ostap/Sites/crm/vendor/orchid/platform/resources/views/layouts/base.blade.php)
`

In my way, path is `/home/ostap/Sites/crm/vendor/orchid/platform/resources/views/layouts/base.blade.php`

We can strip it:

`vendor/orchid/platform/resources/views/layouts/base.blade.php/`

**Comment by Gummibeer** [comment]
Ah, now I see what you mean.
With `base_path()` helper function it should be easy to replace it by an empty string.
Do you want to provide a PR including test?

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/ignition-stackoverflow/releases/tag/1.7.0
